const vscode = require('vscode');
const path = require('path');
const { createPDF } = require('./pdfGenerator');

function getSettings() {
    const config = vscode.workspace.getConfiguration('allToPdf');
    return {
        useGitIgnore: config.get('useGitIgnore', true),
        skipDirs: config.get('exclude', []),
        maxFileSizeKb: config.get('maxFileSizeKb', 1024)
    };
}

async function createPDFWithProgress(folderPath) {
    const settings = getSettings();
    await vscode.window.withProgress({
        location: vscode.ProgressLocation.Notification,
        title: 'Generating PDF...',
        cancellable: false
    }, async () => {
        const { pdfBytes, folderName } = await createPDF(folderPath, settings);
        const outputPath = path.join(folderPath, 'PDF Compiled Project.pdf');
        require('fs-extra').writeFile(outputPath, pdfBytes);
        vscode.window.showInformationMessage('PDF successfully generated by All-to-PDF Extension!');
    });
}

function activate(context) {
    console.log('Congratulations, You can now call the extension by right-clicking the desired project folder and selecting the Compile Folder to PDF option.');

    let disposable = vscode.commands.registerCommand('extension.convertProjectToPDF', async (folder) => {
        if (folder && folder.fsPath) {
            await createPDFWithProgress(folder.fsPath);
        }
    });

    let context_disposable = vscode.commands.registerCommand('extension.convertProjectToPDFContext', async (folder) => {
        if (folder && folder.fsPath) {
            await createPDFWithProgress(folder.fsPath);
        }
    });

    context.subscriptions.push(disposable, context_disposable);
}

function deactivate() {}

module.exports = { activate, deactivate };
